# Generated by Django 5.2.17 on 2026-09-04 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tuman',
                'verbose_name_plural': 'Tumanlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='venues/media/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='venues/gallery/')),
                ('type', models.CharField(choices=[('image', 'Rasm'), ('video', 'Video')], default='image', max_length=10)),
                ('is_main', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Mahsulot media',
                'verbose_name_plural': 'Mahsulot medialari',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Viloyat',
                'verbose_name_plural': 'Viloyatlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='decoration',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['guest_count', 'id']},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ['start_time', 'id']},
        ),
        migrations.AlterModelOptions(
            name='shiftblock',
            options={'ordering': ['date', 'shift_id', 'id']},
        ),
        migrations.AlterModelOptions(
            name='weddinghall',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='package',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shift',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='shiftblock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bar',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='bar',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/covers/'),
        ),
        migrations.AddField(
            model_name='bar',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bar',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/covers/'),
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='map_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weddinghall',
            name='required_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['hall', 'guest_count'], name='package_hall_guests_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['hall', 'is_active'], name='shift_hall_active_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftblock',
            index=models.Index(fields=['hall', 'date'], name='block_hall_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='decoration',
            constraint=models.CheckConstraint(condition=models.Q(('additional_price__gte', 0)), name='decoration_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('hall', 'guest_count'), name='package_hall_guest_count_unique'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='package_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(fields=('hall', 'name'), name='shift_hall_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='shift_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='shiftblock',
            constraint=models.UniqueConstraint(fields=('hall', 'shift', 'date'), name='shift_block_hall_shift_date_unique'),
        ),
        migrations.AddField(
            model_name='bar',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bars', to='venues.district'),
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_halls', to='venues.district'),
        ),
        migrations.AddField(
            model_name='media',
            name='bar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='venues.bar', verbose_name='Bar'),
        ),
        migrations.AddField(
            model_name='media',
            name='hall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='venues.weddinghall', verbose_name='Wedding Hall'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['order', 'name'], name='region_order_name_idx'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='venues.region'),
        ),
        migrations.AddField(
            model_name='bar',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bars', to='venues.region'),
        ),
        migrations.AddField(
            model_name='weddinghall',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wedding_halls', to='venues.region'),
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['region', 'district'], name='bar_region_district_idx'),
        ),
        migrations.AddIndex(
            model_name='bar',
            index=models.Index(fields=['owner', 'created_at'], name='bar_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='weddinghall',
            index=models.Index(fields=['region', 'district'], name='hall_region_district_idx'),
        ),
        migrations.AddIndex(
            model_name='weddinghall',
            index=models.Index(fields=['owner', 'created_at'], name='hall_owner_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_hour__gte', 0)), name='bar_price_per_hour_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='bar',
            constraint=models.CheckConstraint(condition=models.Q(('required_deposit__gte', 0)), name='bar_required_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='weddinghall',
            constraint=models.CheckConstraint(condition=models.Q(('required_deposit__gte', 0)), name='hall_required_deposit_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['hall', 'position'], name='media_hall_position_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['bar', 'position'], name='media_bar_position_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('hall__isnull', False), ('bar__isnull', True)), models.Q(('hall__isnull', True), ('bar__isnull', False)), _connector='OR'), name='media_exactly_one_venue'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['region', 'order'], name='district_region_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='district',
            constraint=models.UniqueConstraint(fields=('region', 'name'), name='district_region_name_unique'),
        ),
    ]
