# Generated by Django 6.0.7 on 2026-07-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, max_length=255, null=True)),
                ('bot_username', models.CharField(blank=True, max_length=100, null=True)),
                ('bot_name', models.CharField(default="To'yxona Admin Bot", max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Bot Config',
                'verbose_name_plural': 'Telegram Bot Config',
            },
        ),
    ]
