# Generated by Django 6.0.7 on 2026-07-16 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_deposit_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('HOLD', 'Muzlatilgan (Hold)'), ('PENDING', 'Kutilmoqda (Pending)'), ('CONFIRMED', 'Tasdiqlangan (Confirmed)'), ('REJECTED', 'Rad etilgan (Rejected)'), ('CANCELLED', 'Bekor qilingan (Cancelled)')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('guest_count', models.PositiveIntegerField(blank=True, null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bar_bookings', to='venues.bar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HallBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_deposit_paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('HOLD', 'Muzlatilgan (Hold)'), ('PENDING', 'Kutilmoqda (Pending)'), ('CONFIRMED', 'Tasdiqlangan (Confirmed)'), ('REJECTED', 'Rad etilgan (Rejected)'), ('CANCELLED', 'Bekor qilingan (Cancelled)')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decoration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_bookings', to='venues.decoration')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to='venues.weddinghall')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to='venues.package')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_bookings', to='venues.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
