# Generated by Django 5.2.17 on 2026-09-04 06:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('venues', '0002_district_media_region_alter_bar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barbooking',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='hallbooking',
            options={'ordering': ['-created_at', 'id']},
        ),
        migrations.AlterField(
            model_name='barbooking',
            name='status',
            field=models.CharField(choices=[('HOLD', 'Hold'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='status',
            field=models.CharField(choices=[('HOLD', 'Hold'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='barbooking',
            index=models.Index(fields=['bar', 'date', 'start_time', 'end_time', 'status'], name='bar_booking_availability_idx'),
        ),
        migrations.AddIndex(
            model_name='barbooking',
            index=models.Index(fields=['user', 'created_at'], name='bar_booking_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='hallbooking',
            index=models.Index(fields=['hall', 'date', 'shift', 'status'], name='hall_booking_availability_idx'),
        ),
        migrations.AddIndex(
            model_name='hallbooking',
            index=models.Index(fields=['user', 'created_at'], name='hall_booking_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='barbooking',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='bar_booking_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='barbooking',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='bar_booking_deposit_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='barbooking',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='bar_booking_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='hallbooking',
            constraint=models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='hall_booking_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='hallbooking',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__gte', 0)), name='hall_booking_deposit_nonnegative'),
        ),
    ]
