# Generated by Django 5.2.17 on 2026-09-04 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_barbooking_options_alter_hallbooking_options_and_more'),
        ('venues', '0002_district_media_region_alter_bar_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='barbooking',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__lte', models.F('total_price'))), name='bar_booking_deposit_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='hallbooking',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_amount__lte', models.F('total_price'))), name='hall_booking_deposit_lte_total'),
        ),
    ]
