# Generated by Django 6.0.7 on 2026-07-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBotConfig',
        ),
    ]
